version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: bitespeed
      POSTGRES_PASSWORD: bitespeed123
      POSTGRES_DB: bitespeed
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
